### ISSUE TITLE
https://ccrma.stanford.edu/~mborins/420b/demo/index.html don't work

### ISSUE THREAD

**Issue by zzz6519003** [MylesBorins/faust2webaudio#1]
Uncaught TypeError: faust.context.createJavaScriptNode is not a functionfaust.noise.that.init @ faust-noise.js:11122faust.noise @ faust-noise.js:11126(anonymous function) @ faust-noise.js:11132

**Comment by MylesBorins** [comment]
Ahhh... webaudio is no longer behind a shim... you can see how old that example is.

Probably not going to have time to fix this atm but thanks for bringing it up!

**Comment by zzz6519003** [comment]
you look cool XD
